# Generated by Django 4.1.4 on 2023-01-27 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approve_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phnum', models.BigIntegerField(blank=True, null=True)),
                ('emp_code', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('emp_code', models.IntegerField(blank=True, null=True)),
                ('phnum', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(default='unknown@gmail.com', max_length=254)),
                ('joining_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 27, 6, 12, 53, 930170, tzinfo=datetime.timezone.utc), null=True)),
                ('password1', models.CharField(blank=True, max_length=100, null=True)),
                ('password2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('phnum', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(default='unknown@gmail.com', max_length=254)),
                ('loan_Ac_num', models.BigIntegerField(blank=True, null=True)),
                ('loan_info', models.TextField(max_length=250)),
                ('password1', models.CharField(blank=True, max_length=100, null=True)),
                ('password2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='request_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phnum', models.BigIntegerField(blank=True, null=True)),
                ('client_code', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('emp_code', models.IntegerField(blank=True, null=True)),
                ('phnum', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(default='unknown@gmail.com', max_length=254)),
                ('Credit_Ac_num', models.BigIntegerField(blank=True, null=True)),
                ('credit_info', models.TextField(max_length=250)),
                ('password1', models.CharField(blank=True, max_length=100, null=True)),
                ('password2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
