# Generated by Django 4.1.4 on 2023-01-27 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='joining_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 27, 6, 13, 27, 202184, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
