# Generated by Django 4.1.4 on 2023-01-27 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_approve_invoice_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approve_invoice',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='request_invoice',
            name='loan',
        ),
        migrations.AddField(
            model_name='approve_invoice',
            name='loan_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request_invoice',
            name='loan_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='joining_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 27, 7, 20, 45, 436104, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
