# Generated by Django 4.1.4 on 2023-01-27 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_deny_invoice_alter_bank_joining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='view_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phnum', models.IntegerField(blank=True, null=True)),
                ('emp_code', models.IntegerField(blank=True, null=True)),
                ('loan_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bank',
            name='joining_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 27, 15, 24, 39, 724745, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
