# Generated by Django 4.1.4 on 2023-01-30 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_view_invoice_alter_bank_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='approve_invoice',
            name='approve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deny_invoice',
            name='approve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='view_invoice',
            name='approve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='joining_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 6, 13, 13, 629447, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
