# Generated by Django 4.1.4 on 2023-01-30 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_approve_invoice_approve_deny_invoice_approve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_code', models.IntegerField(blank=True, null=True)),
                ('in_num', models.IntegerField(blank=True, null=True)),
                ('in_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 12, 16, 7, 554806, tzinfo=datetime.timezone.utc), null=True)),
                ('in_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bank',
            name='joining_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 12, 16, 7, 552658, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
