# Generated by Django 4.1.4 on 2023-01-30 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_upload_invoice_alter_bank_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_invoice',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='joining_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 12, 29, 24, 826380, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='upload_invoice',
            name='in_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 12, 29, 24, 828366, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
