# Generated by Django 4.1.4 on 2023-01-30 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_upload_invoice_currency_alter_bank_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='joining_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 13, 16, 40, 159099, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='upload_invoice',
            name='in_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 30, 13, 16, 40, 162015, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
